services:
  app:
    image: 'bspliter-dev'
    build:
      args:
        - 'target=dev'
    tty: true
    volumes:
      - type: 'bind'
        source: '.'
        target: '/app'
    ports:
      - '8080:8080'
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'bspliter'
      MYSQL_PASSWORD: 'bspliter'
      MYSQL_DATABASE: 'bspliter'
    volumes:
      - type: 'volume'
        source: 'dbdata'
        target: '/var/lib/mysql'
      - type: 'bind'
        source: './my.cnf'
        target: '/etc/mysql/conf.d/my.cnf'
        consistency: 'cached'
    ports:
      - '3306:3306'
volumes:
  dbdata:
