// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: member_to_payment.sql

package db

import (
	"context"
	"database/sql"
)

const createMemberToPayment = `-- name: CreateMemberToPayment :execresult
INSERT INTO member_to_payment (member_id, payment_id) VALUES (?, ?)
`

type CreateMemberToPaymentParams struct {
	MemberID  string
	PaymentID string
}

func (q *Queries) CreateMemberToPayment(ctx context.Context, arg CreateMemberToPaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMemberToPayment, arg.MemberID, arg.PaymentID)
}
