// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Event struct {
	ID   string
	Name string
}

type Member struct {
	ID      string
	Name    string
	EventID string
}

type MemberToPayment struct {
	EventID   string
	MemberID  string
	PaymentID string
}

type Payment struct {
	ID       string
	Name     string
	Amount   int64
	EventID  string
	MemberID string
}
